# config file for netlify to build the project

#build folder to publish + build command
[build]
  publish = "public"
  command = "yarn build"
  functions = "/lambdas"

#build tool versions
[build.environment]
  YARN_VERSION = "1.5.1"
  YARN_FLAGS = "--no-ignore-optional"

[context.production]
  environment = { MC_API_KEY = "21dbe7ebafb605b622a513b450ef788a-us16", MC_LIST_PATH = "https://us16.api.mailchimp.com/3.0/lists/8281a64779/members/" }
