backend:
  name: github
  repo: amir-and-erica/blog
  api_root: https://api.github.com

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Front Image", name: "image", widget: "image", required: "false"}
      - {label: "Social Media title", name: "smTitle", widget: "text" required: "false"}
      - {label: "Color", name: "color", widget: "select", options: ["pink", "purple", "light blue", "dark blue", "yellow", "tan", "orange"], default: "pink"}
      - {label: "Social Media description", name:"smDescription", widget:"text" required: "false"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
